### ISSUE TITLE
Run only on changed files

### ISSUE THREAD

**Issue by abrantes01** [stefanoeb/eslint-action#5]
Hello, 

Is there any ways to run this actions only on changed files (not the entire repository files) ?

**Comment by stefanoeb** [comment]
Hey, not with the current implementation.

However, I'd say it's good to run the whole files at every commit to assure that the repo is 100% valid all the time. What would be nice is to make a pre-commit hook on your case that runs only on changed files (so it's faster) -> see https://github.com/typicode/husky
